### ISSUE TITLE
NAT networks no longer persisted after reboot. but Why?

### ISSUE THREAD

**Issue by kkbruce** [MicrosoftDocs/Virtualization-Documentation#1087]
「NAT networks created on Windows Server 2019 (or above) are no longer persisted after reboot.」

But he did not explain why. How can I do? don't reboot?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 556473c3-3630-dc56-caad-a3d72d34e9e1
* Version Independent ID: 560ad6ca-e017-db71-4605-a73e9f1b8aed
* Content: [Windows container networking](https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-drivers-topologies#feedback)
* Content Source: [virtualization/windowscontainers/container-networking/network-drivers-topologies.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/windowscontainers/container-networking/network-drivers-topologies.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @JMesser81

**Comment by daschott** [comment]
@kkbruce The Docker service is responsible for creating its own default NAT network. This means that upon reboot, the NAT network will only be present after the Docker service has launched again. Containers that were attached to the old NAT network and persist after reboot (e.g. using `--restart always` flag) should re-attach to the new NAT network. 

Please make sure you are using the latest Docker version as any version below Docker engine 18.09.3 on Windows Server 2019 may have problems since it will use the old logic of container attachment.

The reason why this was done is so that users can expect a fresh and clean environment without any leaking network resources after reboot.
