### ISSUE TITLE
host/PRINCIPAL to a gMSA

### ISSUE THREAD

**Issue by vitaprimo** [MicrosoftDocs/Virtualization-Documentation#1791]
What are you talking about!?

Did you copy and paste from somewhere else? Perhaps from the ADFS documentation that has had the same error for about 6 years uncorrected?

Assigning the **host** service **of a domain-joined machine** to anything other than the host itself will break the host association with Active Directory. And this is not something straightforward to fix for somebody that hasn't suffered through this already — because of the misguided documentation and legions of "MPVs" that blindly copy/paste from this as some bible  — because both the host and the domain "think" they're still on. It's not easy or intuitive to leave a domain you can't connect to. And then there's the issue of the lingering delegation, which the user would need to find or else it would be already occupied for the machine to rejoin the domain.

It's almost always the **http** Kerberos service the one needed to be delegated, which is kind of astonishing because it's rather obvious.

Delegating the http service doesn't come without a price, things will stop working on the hosts whose http service is given away, the most immediate ones surely will be losing the ability of PowerShell remoting (Enter-PSSession) and Server Manager won't connect anymore. To avoid this a CNAME must be created in AD (the directory) which is super fast, and easy, and automatically creates and maintains CNAME in AD (the DNS) but this nowhere to be found in the article. This is bad advice which would break the users systems in some way or another.

Windows Server is at six grand, last time I checked and just like Exchange, Skype, SharePoint, etc each new version is trying to pass functionality-removed-and-turned-Azure-subscriptions as new features. The least you can't do is include documentation instead of having your customers chase it, but since you're not doing that; the bare minimum, last-ditch, prentend-to-care-, least you can do is have correct documentation. For that price tag docs should come as a leather-bound coffee table book, not in a badly-written wiki.

And fix ADFS's docs too.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6cbabcb-0910-3082-fe93-bafef68f2faa
* Version Independent ID: 6efd7af0-a3f2-9d4a-cee1-722caf001cdd
* Content: [Create gMSAs for Windows containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts)
* Content Source: [virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md)
* Product: **windows-server**
* Technology: **windows-containers**
* GitHub Login: @rpsqrd
* Microsoft Alias: **jgerend**

**Comment by vrapolinario** [comment]
I'm so, so sorry it took us this long to answer this issue. This should not happen and I sincerely apologize.
Now, can you please clarify where in the documentation you see the issue? Keep in mind that the container is NOT domain-joined. The manual steps we mention you need to do are there because the container is not registering anything. We have tested these instructions and these do work correctly.

**Comment by deedubb** [comment]
I believe the OP is saying you should advocate creating cnames (DNS aliases) for HTTP SPNs rather than replacing SPNs existing on your network because it doesn't say how to revert the setting.

I am a little confused tho because when I try to make a new SPN on my GMSA that has the same value as an existing SPN I get told the SPN must be unique per domain 

That said, deleting the SPN from the servicePrincipalName attribute value on your GMSA account does revert the setting - it might take 15 minutes for AD replication; remember to restart browsers/use new incognito window. You might need to turn on "Advanced Features" in Active Directory Users & Computers (dsa.msc) to see the attributes.

Issue creators: keep on subject, we don't need a rant about Windows Server cost in a windows container issue ticket -- those are different teams @ Microsoft

I think this issue can be closed.
