### ISSUE TITLE
cannot run dotnet container

### ISSUE THREAD

**Issue by ddobric** [MicrosoftDocs/Virtualization-Documentation#373]
When trying to pull or run dotnet image, getting following error:

failed to register layer: re-exec error: exit status 1: output: open \?\C:\Pro
f6f5b647201d4cbb2bda2cae9fb3793904be5aad927fdf4ff4a40\usr\share\man\man3\Locale
 name, or volume label syntax is incorrect.

**Comment by xied75** [comment]
Are you running dotnet on Windows Container? dotnet is a Linux image, it won't run on Windows Container.

**Comment by darrenstahlmsft** [comment]
@xied75 is correct. microsoft/dotnet is a Linux image, and will not run on Windows containers. There was a bug in Docker that failed to check if an image was compatible with the host OS before attempting to unpack it. It has since been fixed to give the correct error message in the latest Docker versions (both 1.12.1 and 1.13-dev have the fix).

If you want to use Dotnet in a Windows container, try using `microsoft/sample-dotnet`

**Comment by enderb-ms** [comment]
Closing this issue since the solution is above.
