### ISSUE TITLE
Hyper-V is not configured to enable processor resource controls

### ISSUE THREAD

**Issue by cassidydotdk** [MicrosoftDocs/Virtualization-Documentation#815]
FWIW, that Hyper-V manager links to _this_ page to explain the above warning message is pretty useless. The UI hint one is given is; "Hey, there's something not optimal in your setup" and the link is sort of a promise that "if you follow this link, we'll explain what you can do".

But then you don't. The page is an architectural overview. It's like a fishing manual when all you really want is some nice fresh salmon ;-)

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: b9533e43-4ff9-0c74-a76f-f6501e7a8009
* Version Independent ID: 40b4f3df-1ec0-fa0c-5a25-f0f2ddb718d3
* Content: [Hyper-V Architecture](https://docs.microsoft.com/da-dk/virtualization/hyper-v-on-windows/reference/hyper-v-architecture)
* Content Source: [virtualization/hyper-v-on-windows/reference/hyper-v-architecture.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/hyper-v-on-windows/reference/hyper-v-architecture.md)
* GitHub Login: @scooley

**Comment by icTaZ** [comment]
Considering politeness, I prefer saying "Not supported on you device" then pointing out to 2 page long description of some architecture without a word.

**Comment by jeffstokes72** [comment]
Agree with previous comments. I'm on a Ryzen 2700x desktop with 64gb of RAM and an array of SSDs. I'm now told I'm not configured properly for processor controls (this seems new in 10 in the last build or two, as this is the first time I've seen it on this hardware, or any hardware, since I started working on Hyper-V and before that Virtual PC).  This article might have merit for some folks, but the link in the hyper-v mmc pointing to this is a sad joke to the end user/administrator :(

**Comment by jeffstokes72** [comment]
https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types#the-root-scheduler

is the area the console should point to apparently.

**Comment by wilsonwill15** [comment]
The last build of Windows 10 broke something in Virtualization

**Comment by computergeek125** [comment]
@wilsonwill15 since this is for the web page not windows 10 itself you may find more helpful results in the Feedback Hub application on windows 10

**Comment by miksan92k** [comment]
@computergeek125 the actual reality is that since Windows 10 has Hyper-V and this appears in the Hyper-V > Processor area, this is the correct area for @wilsonwill15 to post his comment. I don't ever remember seeing this error when I setup Multiple CPU's using Windows 10 1709 Hyper-V

**Comment by computergeek125** [comment]
@miksan92k I'm not denying that Windows 10 supports Hyper-V.  I run it on my personal desktop.  My comment is that this thread is tied to feedback on a _webpage_ not a _product_.  The Feedback Hub is where I thought _product_ feedback would go.

**Comment by miksan92k** [comment]
Understood. My comment was only letting others know that the information is
valid in Windows 10 as well. There are still a lot of people who are not up
to speed enough knowing that Windows 10 Hyper-V exists but it's also
important to know that there are differences between W10 Hyper-V and WS201x
Hyper-V

Hope that makes sense.

**Comment by ruifig2001** [comment]
It is curious that, as the user "miksan92k" indicates:
- until the feature update (b1709, inclusive) the message did not appear (confirm).

To add:
- In the b1709 update I was able to create, install and use x86-based virtual machines from various Linux distributions (included in the list, Debian 8, Ubuntu 14.04, ... unfortunately, I never got the chance to do so with Debian 9 x86 before upgrading to b1803);
- after upgrading to b1803 and progressively, x86 distributions of the Linux editions described above are no more than the first boot menu of the cd / dvd (instead of getting the menu, I get a black screen) ... ;
- from what I could tell, virtual machines already created (and that were working) in b1709 and earlier, also progressively stopped working with the update for b1803, allegedly due to kernel problems)

I have not yet been able to test with b1809 ... as soon as the opportunity allows (even to indicate that everything is still the same), I inform.

**Comment by RyanWAnderson** [comment]
I agree with the OP - this could be improved. The explanation of the architecture was very informative, however the link is titled **Learn more about Hyper-V processor configuration options**. I did not learn anything about the processor configuration options.

If Hyper-V determines that the environment does not support processor resource control, it would be very helpful if the UI could tell us why. _{Required Feature} is not enabled._

**Comment by aoighost** [comment]
Same issue as OP. The latest build broke it and the link is wrong for the error. While it explains how it works, it doesn't say anything on how to fix it.

**Comment by jeffstokes72** [comment]
Oh wow, this still hasn't been fixed? wth

**Comment by jeffstokes72** [comment]
Created a feedback item for this.

![image](https://user-images.githubusercontent.com/9102841/49692257-4fbd4a80-fb24-11e8-8458-ada6dfe8087d.png)

**Comment by cabellonnovie** [comment]
I will try to give what I know regarding the dreaded "Hyper-V is not configured to enable processor resource controls". This notification appears in Hyper-V VM CPU Settings if you have updated your Windows 10 to version 1803. 

The "Hyper-V is not configured to enable processor resource controls" is indicating that Hyper-V is no longer managing the CPU resource for the VMs. Since Windows 10 version 1803, the CPU resource is managed by the host OS (root partition).

The CPU resource management for VMs are called "scheduler". The original scheduler in previous Windows versions is called "Classic Scheduler", and in Windows 10 version 1803 this has been changed to the new "Root Scheduler" as default scheduler for Hyper-V.

I guess this change is implemented by Microsoft after the discovery of "Spectre and Meltdown" vulnerabilities.

The negative impact of "Root Scheduler" is the high CPU overhead. In my experience, a single VM can reach 100% CPU load. Root Scheduler is less efficient compared to Classic Scheduler. If you are running VMs in Root Scheduler mode, you can see a task/process in the Task Manager named "Vmmem" consuming a lot of CPU and Memory resource. 

The benefit of using "Root Scheduler" is high degree of isolation. They said that Windows Defender is now deeply integrated to the OS with Root Scheduler (I am not sure) and it scans for anomalies in system memory that might be caused by infected VMs.

In case you are asking if you can revert to Classic Scheduler, I think you can, but Microsoft said that "Root Scheduler is the only supported scheduler in Windows 10 1803 and onwards". But in my experience, changing the default scheduler does not make much difference. Maybe you can try and post your results here.

I have tried reverting Root Scheduler to Classic Scheduler in Windows 10 version 1803 and the "Hyper-V is not configured to enable processor resource controls" is gone, but the Vmmem in the task manager still exist and CPU still reach 100% when a single VM is at heavy workloads. I upgraded to Windows 10 version 1809 and reverted to Classic Scheduler, and both the "Hyper-V is not configured to enable processor resource controls" and "Vmmem" are gone, but the CPU still reaches 70% even the VM is set to 25% CPU.

Here are the things you need to do to change to different schedulers(note: This is provided as is. I am not responsible for any damages that may result in undertaking the process below):

1.) First, verify your default scheduler. You can verify by running this PowerShell script:
`Get-WinEvent -FilterHashTable @{ProviderName="Microsoft-Windows-Hyper-V-Hypervisor"; ID=2} -MaxEvents 1`

2.) PowerShell will give you a 0x code. The 0x code corresponds to the current scheduler mode used by Hyper-V as default. You can identify the 0x code using the following:
0x Codes:
1 = Classic scheduler, SMT disabled
2 = Classic scheduler
3 = Core scheduler
4 = Root scheduler

3.) If you wish to proceed to revert to the classic scheduler, you can use this script in an elevated(admin) PowerShell:
`bcdedit /set hypervisorschedulertype classic`

4.) And after you made the tests, if you wish to return to the default Root Scheduler, run the script:
`bcdedit /deletevalue hypervisorschedulertype`

**Comment by cbj4074** [comment]
The UI says:

> Hyper-V is not configured to enable processor resource controls.

1. How then shall I configure Hyper-V to enable processor resource controls? It's not clear whether my hardware doesn't support the feature, or whether the feature is supported only on Windows Server, or if I simply didn't check a box somewhere to enable the feature in software.
2. Why aren't the relevant fields disabled in the UI? Is the implication that I can change the values but doing so won't have any effect? That seems rather pointless.
3. As many others have noted, the message hyperlinks to a page that explains nothing about Hyper-V processor configuration options (the page provides only a high-level architectural overview).

@cabellonnovie Thank you for what is by far the most useful contribution thus far.

Tangentially related: on version 1803, I can corroborate everything you say, with one (mostly trivial) exception: the `vmmem` process consumes only 4K of apparent memory (though, I suspect, as you suggest, that it reserves the amount allocated to the guest machine in one form or another). Similarly, its apparent CPU consumption is at most 10%, yet the CPU graph on the Task Manager's Performance tab often is at 100%, with no apparent accounting for the usage.

Basically, it seems that the guest VM's memory and CPU usage are reflected in the Performance stats, but not in any specific process. This is in no way intuitive because the `System Idle Process` might show 20%, but CPU usage on the Performance tab is at 100%. It seems that the numbers should add-up in some logical capacity.

**Comment by jeffstokes72** [comment]
If hyper-v is enabled, your session is a VM. Your perfmon is inaccurate as
a result.

https://blogs.msdn.microsoft.com/virtual_pc_guy/2008/02/28/hyper-v-virtual-machine-cpu-usage-and-task-manager/

**Comment by mountswolmore** [comment]
I'm pretty sure these issues started after 1607.

W10-1607 Everything fine. 1703 and newer, starting VMs kills parity storage space.
I had 8 2tb disks in a parity space on 1607 and everything was great.



Windows update forced 1703 on me and things broke. When starting the VMs, they sit at a black screen with the space at 100% activity moving 0 data until the storage space goes offline due to critical write failure. If I try to power off the VMs, they just sit there "Stopping" until the space goes offline. Even rebooting the host just sits there until the space comes offline. I rolled back to 1607 and disabled updates.



Forward a few months and my system updates itself to 1803 and the issue comes back, only I can't go back to 1607 and reinstalling the host every few months doesn't seem like a good plan.



All disks are fine individually and show no issues. Only error in event viewer is that the pool went offline. It comes right back online and all the data works fine until you try to start VMs again.



I changed the hyper-v scheduler type, disable hyper threadding, killed C states, set VMs to a single core, disabled dynamic RAM, and a dozen other things.

It just seems like VMs+ parity spaces are totally broken. I created a mirror pool and while they run like garbage, they did boot. Being the disks were from 2010, I thought it might just be time to replace them. I used diskspeed to bench the disks solo and every one of them out performed the parity pool of 7 other disks... which simply shouldn't happen with read tests.



Despite it not seeming like the disks, I went from 7.2k 2TB 32mb cache 3gbps disks to 7.2k 4tb 256mb cache 6gbps disks and not a damn thing changed. Starting 2 single core VMs with 2048mb of ram takes down my parity space of locking up for 20 minutes.



Just wondering if anyone has stumbled into anything like this.



Also, contacting microsoft support only results in losing 4 hours of your life for them to go "oh, it's a vm, give us $500." I cannot adequately convey my rage at the gross incompetence of microsoft's support and I just wish there was more I could do than whine about it on Reddit. It's absolute garbage.

**Comment by notanartist** [comment]
here I have the following behavior:
Hyper-V gives me the same error as you get (virtualization support not enabled), however, within the VM I actually have all the Cores that I set up.
The error message appears to be new. ..so I can back the people who suggest that some windows update recently broke stuff.

**Comment by danieleusebio** [comment]
Completely agree with Cassidydotdk

**Comment by silence48** [comment]
this is fucking stupid. i'm so fed up with windows updates that are FEATURE updates that break shit.  I KNOW this used to work and now suddenly it doesn't!

**Comment by johncslack** [comment]
Hey Folks,

Thank you for pointing out this issue and raising it in feedback hub.  I have updated the link in Hyper-V manager to point to the appropriate section of our documentation: https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types#virtual-machine-cpu-resource-controls-and-the-root-scheduler

This page outlines the different scheduler types Hyper-V can use, and explains why processor resource controls are not available while the root scheduler is in use.

Thanks,
John Slack
