### ISSUE TITLE
Update Debug-ContainerHost script

### ISSUE THREAD

**Issue by stgraves** [MicrosoftDocs/Virtualization-Documentation#862]
The PowerShell script needs to be updated since 2019 has been released.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20bcd7e2-045f-843b-4fae-82ef2f51acff
* Version Independent ID: 22122208-ec01-83ae-d45a-995d1acc3894
* Content: [Troubleshooting Windows Containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/troubleshooting)
* Content Source: [virtualization/windowscontainers/troubleshooting.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/troubleshooting.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @PatrickLang

**Comment by ekitagawa** [comment]
+1 from Docker support team.  This version fails on Windows 1803 due to lack of `Get-VMSwitch`.

**Comment by stgraves** [comment]
The script does not check for images pulled down from mcr.microsoft.com/…. so it throws an error because it cannot find a Microsoft/windowsservercore or Microsoft/nanserver image.

**Comment by cwilhit** [comment]
@ekitagawa - can you open a new issue for the VM-Switch on 1803 issue?

**Comment by ekitagawa** [comment]
@cwilhit I can do that.  But if it's fixed for Win 2019, I wouldn't bother you too much over this given that 1803 is on a semi-annual channel...  We could document this and ask customers to upgrade.  Majority of our customer used 1709 and 1803 because 2016 engine lacked many critical functionalities.  Generally speaking, customer prefer long term channel.
