### ISSUE TITLE
Running Kubernetes as Service

### ISSUE THREAD

**Issue by adagioajanes** [MicrosoftDocs/Virtualization-Documentation#949]
This document explains that I can configure kubernetes to run in the background as a service. Can you expand upon that? start.ps1 has alot to it that needs to be considered if setting this up to run as a service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d162332-10db-b9f2-92cc-19475ca448ed
* Version Independent ID: 82e7e978-51d0-e563-87bf-e0c82c2bb04a
* Content: [Troubleshooting Kubernetes](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/common-problems)
* Content Source: [virtualization/windowscontainers/kubernetes/common-problems.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/windowscontainers/kubernetes/common-problems.md)
* Product: **containers**
* GitHub Login: @gkudra-msft
* Microsoft Alias: **gekudray**

**Comment by daschott** [comment]
@adagioajanes Rough instructions on how to set this up will be included in the next docs update. We will take some of the functionality out of start.ps1 and move it into a install.ps1 script so that you can run 
1 .\install.ps1 <configuration options>
2. .\register-svc.ps1 <configuration options> or .\start.ps1 <configuration  options>

For now, assuming you have run start.ps1 previously, you can run stop.ps1 and then use nssm.exe to launch binary of your choice as a service [similar to this](https://github.com/Microsoft/SDN/pull/312#issuecomment-461636217)

**Comment by daschott** [comment]
@adagioajanes Rough instructions for this have been added here now: https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/kube-windows-services

**Comment by daschott** [comment]
There is also more work being done for automatically launching this as a service: https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/kubeadm/Kubecluster.md
